config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :orders
  resources :services
  resources :performers
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :services

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :services

  validates :customer_name, presence: true

  has_many :services_orders
  has_many :services, through: :services_orders
end

app/models/performer.rb
class Performer < ApplicationRecord
  belongs_to :service

end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :order
  belongs_to :category
  has_one :performer

  has_many :services_orders
  has_many :orders, through: :services_orders
end

app/models/services_order.rb
class ServicesOrder < ActiveRecord::Base
  belongs_to :order
  belongs_to :service
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.order(params[:sort])
  end

  def new
    @category = Category.new
  end

  def create
    # debugger
    @category = Category.new(category_params)

    if @category.save
      redirect_to category_path(@category)
      flash[:success] = 'success'
    else
      render :new
      flash[:success] = 'failure'
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to category_path(@category)
      flash[:success] = 'success'
    else
      render :edit
      flash[:success] = 'failure'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      redirect_to root_path
    else
      redirect_to category_path(@category)
    end
  end

  private

  def category_params
    params.require(:category).permit(:title, :category,:performer)
    #require заберёт из парамса те данные, которые касаются статьи category
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.order(params[:sort])
  end

  def new
    @order = Order.new
  end

  def create
    # debugger
    @order = Order.new(order_params)

    if @order.save
      redirect_to order_path(@order)
      flash[:success] = 'success'
    else
      render :new
      flash[:success] = 'failure'
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])

    if @order.update(order_params)
      redirect_to order_path(@order)
      flash[:success] = 'success'
    else
      render :edit
      flash[:success] = 'failure'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    if @order.destroy
      redirect_to root_path
    else
      redirect_to order_path(@order)
    end
  end

  private

  def order_params
    params.require(:order).permit(:customer_name, service_ids: [])
  end
end

app/controllers/performers_controller.rb
class PerformersController < ApplicationController
  def index
    @performers = Performer.order(params[:sort])
  end

  def new
    @performer = Performer.new
  end

  def create
    # debugger
    @performer = Performer.new(performer_params)

    if @performer.save
      redirect_to performer_path(@performer)
      flash[:success] = 'success'
    else
      render :new
      flash[:success] = 'failure'
    end
  end

  def show
    @performer = Performer.find(params[:id])
  end

  def edit
    @performer = Performer.find(params[:id])
  end

  def update
    @performer = Performer.find(params[:id])

    if @performer.update(performer_params)
      redirect_to performer_path(@performer)
      flash[:success] = 'success'
    else
      render :edit
      flash[:success] = 'failure'
    end
  end

  def destroy
    @performer = performer.find(params[:id])
    if @performer.destroy
      redirect_to root_path
    else
      redirect_to performer_path(@performer)
    end
  end

  private

  def performer_params
    params.require(:performer).permit(:name)
    #require заберёт из парамса те данные, которые касаются статьи performer
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services = Service.order(params[:sort])
  end

  def new
    @service = Service.new
  end

  def create
    # debugger
    @service = Service.new(service_params)

    if @service.save
      redirect_to service_path(@service)
      flash[:success] = 'success'
    else
      render :new
      flash[:success] = 'failure'
    end
  end

  def show
    @service = Service.find(params[:id])
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])

    if @service.update(service_params)
      redirect_to service_path(@service)
      flash[:success] = 'success'
    else
      render :edit
      flash[:success] = 'failure'
    end
  end

  def destroy
    @service = Service.find(params[:id])
    if @service.destroy
      redirect_to root_path
    else
      redirect_to service_path(@service)
    end
  end

  private

  def service_params
    params.require(:service).permit(:title, :order)
    #require заберёт из парамса те данные, которые касаются статьи service
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/performers_helper.rb
module PerformersHelper
end

app/helpers/service_categories_helper.rb
module ServiceCategoriesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/categories/edit.html.erb
<br>
<%= form_with(model: @category) do |form| %>

  <%#= @user.errors.full_messages.join(", ") if @user.errors.present? %>

  <% @category.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>

  <div>
    <%= form.label :category_title %>
    <%= form.text_field :title %>
  </div>
  <hr>

  <hr>

  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/index.html.erb
<br>
<%= link_to 'Main page', root_path %>
<br>
<hr>
<%= link_to 'new category', new_category_path %>
<hr>

<h3>categories</h3>
<table class="table">
  <thead>
  <tr >
    <th class="col-lg-1"><%= link_to "Id", :sort => "id"%> </th>
    <th class="col-lg-1"><%= link_to "Category Title", :sort => "category_name"%> </th>
    <th class="col-lg-1 text-right"><%= link_to "Created at", :sort => "created_at"%> </th>
  </tr>
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.id %></td>
      <td><%= link_to "#{category.title}", category_path(category.id) %></td><td>
      <td><%= category.created_at %></td>
    </tr>
  <% end %>
  </thead>
</table>
<hr>

app/views/categories/new.html.erb
<br />
<%= link_to 'back to categories', categories_path %>
<h1>
  New category
</h1>
<%= form_with(model: @category) do |form| %>

  <%#= @user.errors.full_messages.join(", ") if @user.errors.present? %>

  <% @category.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <hr>

  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/show.html.erb
<br />
<%= link_to 'back to categories', root_path %>
<br />
<h1>
  Category №
  <%= @category.id %>
</h1>
<p>
  <%= @category.title %>
</p>
<p>
  <%=   %>
</p>
<p>
  <%=   %>
</p>
<p>
  <small>
    created at
    <%= @category.created_at.in_time_zone('Moscow').strftime("%H:%m %d.%m.%Y") %>
  </small></p>
<%= link_to 'edit', edit_category_path(@category.id) %>
<%= link_to 'delete', category_path(@category.id), method: :delete, data: { confirm: 'are you sure?'} %>
<hr />
<hr />
<hr />

app/views/common/errors.html.erb
<% if resource.errors.any? %>
  <div id=errors_explanation">
    <h2><%= pluralize(resource.errors.count, "error") %> prohibited this order from being saved:</h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Autoservice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <%= render 'common/errors', resource: @order %>

  <div class="field" >
    <%= f.label :customer_name %>
    <%= f.text_field :customer_name %>
  </div>
  <div class="actions">
    <%= f.submit "#{ @order.new_record? ? 'Create' : 'Change' }" %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<br>
<%= form_with(model: @order) do |form| %>

  <%#= @user.errors.full_messages.join(", ") if @user.errors.present? %>

  <% @order.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>

  <div class="field">
    <%= form.label :customer_name %>
    <%= form.text_field :customer_name %>
  </div>
  <hr>

  <div class="field">
    <br>
    <%= form.label :service, 'Service'%>
    <%= form.collection_select :service_ids, Service.all, :id, :title, {}, { multiple: true }%>
  </div>
  <hr>

<!--  <div>-->
<!--    <br>-->
    <%#= form.label :Performer %>
    <%#= form.collection_select :performer, Performer.all, :id, :name%>
<!--  </div>-->
  <hr>

  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/index.html.erb
<br>
<%= link_to 'Main page', root_path %>
<br>
<hr>
<%= link_to 'new order', new_order_path %>
<hr>

<h3>Orders</h3>
<table class="table">
  <thead>
    <tr >
      <th class="col-lg-1"><%= link_to "Id", :sort => "id"%> </th>
      <th class="col-lg-1"><%= link_to "Customer Name", :sort => "customer_name"%> </th>
      <th class="col-lg-1 text-right"><%= link_to "Created at", :sort => "created_at"%> </th>
    </tr>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= link_to "#{order.customer_name}", order_path(order.id) %></td><td>
        <td><%= order.created_at %></td>
      </tr>
    <% end %>
  </thead>
</table>
<hr>

app/views/orders/new.html.erb
<br />
<%= link_to 'back to categories', categories_path %>
<h1>
  New category
</h1>
<%= form_with(model: @order) do |form| %>

  <%#= @user.errors.full_messages.join(", ") if @user.errors.present? %>

  <% @order.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>

  <div>
    <%= form.label :customer_name %>
    <%= form.text_field :customer_name %>
  </div>
<br>
  <div>
    <%= form.label :service %>
    <%= form.collection_select :service_ids, Service.all, :id, :title, {}, { multiple: true } %>
  </div>

  <hr>

  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/show.html.erb
<br />
<%= link_to 'back to orders', orders_path %>
<br />
<h3>
  Order №
  <%= @order.id %>
</h3>

<h4>Customer name
  <%= @order.customer_name %>
</h4>
<br>
Services:
<br>
<% @order.services.each do |s| %>
  <br>
  service title:
  <%= s&.title %>
  <br>
  performer name:
  <%= s&.performer&.name %>
  <br>
  <hr>
<% end %>

<p>
  <small>
    created at
    <%= @order.created_at.in_time_zone('Moscow').strftime("%H:%m %d.%m.%Y") %>
  </small></p>
<%= link_to 'edit', edit_order_path(@order.id) %>
<%= link_to 'delete', order_path(@order.id), method: :delete, data: { confirm: 'are you sure?'} %>
<hr />
<hr />
<hr />

app/views/performers/edit.html.erb
<br>
<%= form_with(model: @performer) do |form| %>

  <%#= @user.errors.full_messages.join(", ") if @user.errors.present? %>

  <% @performer.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <hr>

  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/performers/index.html.erb
<br>
<%= link_to 'Main page', root_path %>
<br>
<hr>
<%= link_to 'new performer', new_performer_path %>
<hr>

<h3>performers</h3>
<table class="table">
  <thead>
  <tr >
    <th class="col-lg-1"><%= link_to "Id", :sort => "id"%> </th>
    <th class="col-lg-1"><%= link_to "Performer Name", :sort => "performer_name"%> </th>
    <th class="col-lg-1 text-right"><%= link_to "Created at", :sort => "created_at"%> </th>
  </tr>
  <% @performers.each do |performer| %>
    <tr>
      <td><%= performer.id %></td>
      <td><%= link_to "#{performer.name}", performer_path(performer.id) %></td><td>
      <td><%= performer.created_at %></td>
    </tr>
  <% end %>
  </thead>
</table>
<hr>

app/views/performers/show.html.erb
<br />
<%= link_to 'back to performers', performers_path %>
<br />
<h2>
  performer №
  <%= @performer.id %>
</h2>
<p>Performer name: <%= @performer.name %></p>
<p>Order №: <%= @performer.service.order.customer_name %></p>
<p>Service №: <%= @performer.service.id %></p>

  <p>
  <small>
    created at
    <%= @performer.created_at.in_time_zone('Moscow').strftime("%H:%m %d.%m.%Y") %>
  </small></p>
<%= link_to 'edit', edit_performer_path(@performer.id) %>
<%= link_to 'delete', service_path(@service.id), method: :delete, data: { confirm: 'are you sure?'} %>
<hr />
<hr />
<hr />

app/views/services/edit.html.erb
<br>
<%= form_with(model: @service) do |form| %>

  <%#= @user.errors.full_messages.join(", ") if @user.errors.present? %>

  <% @service.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <hr>
  <div>
    <%= form.label :service_category %>
    <%= form.collection_select :category, Category.all, :id, :title%>
  </div>
  <hr>
  <div>
    <%= form.label :performer %>
    <%= form.collection_select :performer, Performer.all, :id, :name%>
  </div>
  <br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/services/index.html.erb
<br>
<%= link_to 'Main page', root_path %>
<br>
<hr>
<%= link_to 'new service', new_service_path %>
<hr>

<h3>services</h3>
<table class="table">
  <thead>
  <tr >
    <th class="col-lg-1"><%= link_to "Id", :sort => "id"%> </th>
    <th class="col-lg-1"><%= link_to "Title", :sort => "title"%> </th>
    <th class="col-lg-1"><%= "Category" %> </th>
    <th class="col-lg-1 text-right"><%= link_to "Created at", :sort => "created_at"%> </th>
  </tr>
  <% @services.each do |service| %>
    <tr>
      <td><%= service.id %></td>
      <td><%= link_to "#{service.title}", service_path(service.id) %></td><td>
      <td><%= service.category&.title %></td><td>
      <td><%= service.created_at %></td>
    </tr>
  <% end %>
  </thead>
</table>
<hr>

app/views/services/new.html.erb
<br />
<%= link_to 'back to services', services_path %>
<h1>
  New service
</h1>
<%= form_with(model: @service) do |form| %>

  <%#= @user.errors.full_messages.join(", ") if @user.errors.present? %>

  <% @service.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :order %>
    <%= form.collection_select :order, Order.all, :id, :customer_name%>
  </div>
  <hr>

  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/services/show.html.erb
<br />
<%= link_to 'back to services', root_path %>
<br />
<h1>
  Service №
  <%= @service.id %>
</h1>
<p>
  service title:
  <%= @service.title %>
  <br>
  service category:
  <%= @service.category&.title %>
  <br>
  performer name:
  <%= @service.performer&.name %>
  <br>
  <%=  %>
</p>
<p>
  <%=   %>
</p>
<p>
  <%=   %>
</p>
<p>
  <small>
    created at
    <%= @service.created_at.in_time_zone('Moscow').strftime("%H:%m %d.%m.%Y") %>
  </small></p>
<%= link_to 'edit', edit_service_path(@service.id) %>
<br>
<%= link_to 'delete', service_path(@service.id), method: :delete, data: { confirm: 'are you sure?'} %>
<hr />
<hr />
<hr />

app/views/welcome/index.html.erb
<h1>Autoservice</h1>

<div>
  <ul>
    <li><%= link_to t('orders'), orders_path %></li>
    <li><%= link_to t('services'), services_path %></li>
    <li><%= link_to t('performers'), performers_path %></li>
    <li><%= link_to t('categories'), categories_path %></li>
  </ul>
</div>